# Generated by Django 5.2.3 on 2025-07-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationDefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contours_rule_1_vide', models.IntegerField(default=35)),
                ('area_ratio_rule_1_vide', models.FloatField(default=0.25)),
                ('mean_gray_rule_2_vide', models.IntegerField(default=140)),
                ('edge_density_rule_2_vide', models.FloatField(default=0.05)),
                ('area_ratio_rule_3_vide', models.FloatField(default=0.1)),
                ('edge_density_rule_3_vide', models.FloatField(default=0.02)),
                ('center_contour_density_rule_4_vide', models.FloatField(default=0.2)),
                ('zone_middle_mean_brightness_rule_4_vide', models.IntegerField(default=70)),
                ('mean_saturation_rule_1_pleine', models.IntegerField(default=75)),
                ('area_ratio_rule_1_pleine', models.FloatField(default=0.2)),
                ('area_ratio_rule_2_pleine', models.FloatField(default=0.3)),
                ('num_contours_rule_2_pleine', models.IntegerField(default=60)),
                ('edge_density_rule_3_pleine', models.FloatField(default=0.05)),
                ('mean_saturation_rule_3_pleine', models.IntegerField(default=75)),
                ('center_contour_density_rule_4_pleine', models.FloatField(default=0.35)),
                ('zone_middle_mean_brightness_rule_4_pleine', models.IntegerField(default=80)),
                ('contrast_rule_5_pleine', models.IntegerField(default=50)),
                ('entropy_rule_5_pleine', models.FloatField(default=7.0)),
                ('is_full_score', models.IntegerField(default=2)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('annotation', models.CharField(blank=True, choices=[('vide', 'Vide'), ('moitie', 'À moitié pleine'), ('pleine', 'Pleine'), ('debordante', 'Débordante'), ('depot_sauvage', 'Dépôt sauvage')], max_length=20, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('largeur', models.IntegerField(blank=True, null=True)),
                ('hauteur', models.IntegerField(blank=True, null=True)),
                ('taille_ko', models.IntegerField(blank=True, null=True)),
                ('r_moyen', models.IntegerField(blank=True, null=True)),
                ('v_moyen', models.IntegerField(blank=True, null=True)),
                ('b_moyen', models.IntegerField(blank=True, null=True)),
                ('luminance_moyenne', models.FloatField(blank=True, null=True)),
                ('has_contours', models.BooleanField(blank=True, null=True)),
                ('contraste', models.FloatField(blank=True, null=True)),
                ('histogramme', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneRisques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date_debut_validite', models.DateField(blank=True, null=True)),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('niveau', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='analyse.image')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyse.zonerisques')),
            ],
        ),
    ]
